### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by joshgoebel** [joshgoebel/wren-essentials#6]
This is very likely to change with the ebb and flow.  For discussion see issue #7.

- [x] JSON (via `pdjson.c`) #5
- [x] `Strings.globMatch`
- [ ] Regular expressions (via [un-TCLed regex](https://github.com/garyhouston/hsrex)?) PCRE?
- [ ] Date/Time
- [ ] Enforce - param validation
- [ ] Hash (md5, sha1, crc32, etc) - https://github.com/blade-lang/blade ?
